ZTL-ARTCC/Current_Website

app/Announcement.php, app/Console/Commands/UpdateSoloCerts.php, app/Http/Controllers/AdminDash.php, app/Http/Controllers/ControllerDash.php, app/Http/Controllers/FrontController.php, app/Http/Controllers/TrainingDash.php, app/TrainingTicket.php, database/migrations/2018_08_08_155656_calendar.php, database/migrations/2019_07_24_184431_calendar_update.php, package-lock.json, resources/views/dashboard/admin/calendar/index.blade.php, resources/views/dashboard/dashboard.blade.php, resources/views/dashboard/training/new_ticket.blade.php, resources/views/site/staff.blade.php, routes/web.php
Added ability to hide calendar events, and added a 'No Show' option to training tickets (also amended a controller to prevent 'OTS' notifications to the TA if they are a no show).
**Not Tested**
=> Training Ticket Update, News/Announcement visiblity

app/Console/Commands/RosterUpdate.php, app/Console/Commands/VisitAgreement.php
This fixes the roster update on the website. Just a small change from a change in VATUSA API.
=> Fix Roster Update

app/Console/Commands/RosterUpdate.php, app/Http/Controllers/AdminDash.php, app/Http/Controllers/FrontController.php, app/Http/Controllers/TrainingDash.php, app/TrainingTicket.php, database/migrations/2019_07_24_184431_calendar_update.php, resources/views/dashboard/admin/calendar/index.blade.php, routes/web.php
The audit log was attempting to put the entire user variable (decoded) into the audit log. Fixed by just putting the users full name.
=> Fixed OTS Assignment Issue

app/EventRegistration.php, app/Http/Controllers/ControllerDash.php, app/User.php, resources/views/dashboard/controllers/events/view.blade.php, resources/views/dashboard/dashboard.blade.php
Merge for the events rework. No migrating needed.
=> Events rework

app/Chat.php, app/Http/Controllers/ChatController.php, database/migrations/2019_08_20_082011_chat.php, resources/views/inc/chat.blade.php, resources/views/inc/sidebar.blade.php, resources/views/layouts/dashboard.blade.php, routes/web.php
This completes the chat addition to the website.
=> Add chat to website

database/seeds/MoodleCourses.php
Simplify the moodle user adding flow. This now works since users have to login to the website in order to access moodle.
=> Finish the moodle rework

resources/views/dashboard/admin/bronze-mic.blade.php
Reverts ZTLARTCC/ZTL_website#91
=> Revert "Update bronze-mic.blade.php"

app/Console/Kernel.php
Removes scheduled events reminder
=> closes #105

resources/views/site/roster.blade.php
- Now will only display visiting controller if their status is `!= 2`
=> fixes #110

app/Http/Controllers/AdminDash.php
Notifies visitors that they have been removed from the roster.
=> Roster removal notification

resources/views/dashboard/controllers/roster.blade.php, resources/views/site/roster.blade.php
=> April fools!

app/Console/Commands/OnlineControllerUpdate.php
trying to update old code to work with new system
=> Update to use Json

app/Http/Controllers/AdminDash.php, app/Http/Controllers/FrontController.php, app/User.php, resources/views/dashboard/admin/roster/new_vis.blade.php
This branch creates new functionality in the visitor request and roster control elements.
=> Prevent duplicate roster entries

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/story-template---internal-use-only.md
This PR will:
* Add issues templates for creating a story, reporting a bug, and requesting a new feature
=> Add issues templates

resources/views/emails/visit/new.blade.php
This PR:
* Updates visitor email template IAW Eli's request
=> Update the visitor email template

.github/workflows/build-and-deploy.yml, .github/workflows/build.yml, .github/workflows/deploy.yml
**DO NOT MERGE.** The environments are not completely setup yet, and testing must be done on master before this can be considered stable.
This PR will:
* Add GitHub actions to build and deploy to the following environments:
* `prod` (https://www.ztlartcc.org) - manual deploy from master only
* `stag` (https://stag.ztlartcc.org) - auto deploy on push to master
* `qa-1` (https://qa-1.ztlartcc.org) - manual deploy only, from any branch
* `qa-2` (https://qa-2.ztlartcc.org) - manual deploy only, from any branch
* Opening a PR will build to make sure there are no building errors, but will not deploy to any environment
* Close #170 
Before merging into master, this should be rebased with master AFTER the #176 is merged. This assumes that JavaScript dependencies are up to date (this is the reason …
=> GitHub Actions Build and Deploy

app/Http/Controllers/RosterController.php
This PR will:
* Set production environment to redirect to proper login URL based on env
=> NOISS Fix login to use production url based on env

app/Console/Commands/RosterUpdate.php, app/Http/Controllers/AdminDash.php, app/User.php
This PR will:
* Fix the initials assignment bug
* Moves this method into the `User.php` model
* Remove clutter from `RosterUpdate.php`
* Remove controller initials for controllers that are marked as inactive on the roster
* Close #184
=> #184 Fix initials assignment

app/Http/Controllers/TrainingDash.php, resources/views/dashboard/training/tickets.blade.php
Updated logic in tickets.blade.php to check if array key exists before utilizing the array key. Also updated code indent/formatting throughout the file.
=> Fix vatusa exam display bug

resources/views/site/pilot_guide_atl.blade.php
This PR will:
* Updates bullet to reflect proper runway id 9L/27R
* Close #188
=> #188 Fixes runway typo

resources/views/site/home.blade.php
This PR will:
* Fixes home page right-side widget text color (currently black, fixes text color to white for readability)
* Removes dev code in home.blade.php
* Close #194
=> Fix widget style

database/migrations/2022_11_09_013847_create_mentor_training_times_table.php, database/migrations/2022_11_09_013917_update_files_table.php, database/migrations/2022_11_09_013928_update_roster_table.php, database/migrations/2022_11_09_013941_update_training_tickets_table.php, database/migrations/2022_11_09_014000_update_visit_requests_table.php
This PR will:
* Add missing migrations for table creations and updates that occurred in prod
* Close #192
=> #192 Add missing migrations

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
This PR will:
* Add a codeowners file
* Add PR template
=> NOISS Add codeowners and PR template

.github/workflows/build.yml
This PR will:
* Add workflow dependencies required for building #226 to build
=> #221 Add php workflow dependencies

resources/views/dashboard/controllers/roster.blade.php, resources/views/site/roster.blade.php
This PR will:
* Adds AWM tag to roster
* Removes old visit agreement code segments that were commented
=> NOISS Roster cleanup

app/Http/Controllers/Auth/LoginController.php
This PR will:
* Fix the realops issue where users external of VATUSA cannot log into realops
=> #238 Fix VATUSA external users login to realops

app/Http/Controllers/FrontController.php
Changed recieved to received
This PR will:
* Fixes "received" spelling error in feedback return message
* Close #215
=> #215 Fixed spelling error

.github/ISSUE_TEMPLATE/story-template---internal-use-only.md
This PR will:
* Add a toggle section to the story template
=> NOISS Add toggle section to story template

app/Http/Controllers/TrainingDash.php, resources/views/dashboard/training/tickets.blade.php
This PR will:
* Refreshes the exam score display
* Adds type protection to variables in the exam score API pull
* Removes the deprecated VATUSA API /exam endpoint calls
* Close #242 
* Close #244
=> Rework vatusa exam pull

resources/views/site/pilot_guide_atl.blade.php
This PR will:
* [...]
* Close #239
=> #239 Fix American airlines D gates in pilot guide

app/RealopsFlight.php, resources/views/dashboard/admin/realops/create.blade.php, resources/views/dashboard/admin/realops/edit.blade.php
This PR will:
* Adds datepicker JS to realops flight add/edit views
* Close #230
=> #230 Adds datepicker logic to realops flight add/edit

resources/views/dashboard/admin/feedback.blade.php
This PR will:
* Remove extra pilot column from new feedback table
* Close #245
=> #245 Fixes new feedback table columns

database/migrations/2023_02_11_125330_chat_remove.php
This PR will:
* Fix the migration class name to remove chat table
=> NOISS Fix migration class name to remove chat table

resources/assets/js/app.js
This PR will:
* Fixes a bug that was causing the site to double-load JS assets including JQuery
=> NOISS: Removes double-import of bootstrap JS assets

resources/views/layouts/master.blade.php
This PR will:
* Fix the recaptcha not showing
=> NOISS Fix recaptcha not showing

resources/views/layouts/dashboard.blade.php
This PR will:
* Removes duplicative jQuery library import
* Prevents site from throwing this error: Failed to find a valid digest in the 'integrity' attribute for resource https://code.jquery.com/jquery-3.4.1.min.js' with computed SHA-256 integrity 'CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo='. The resource has been blocked.
* Close #266
=> #266 Fixes jQuery error

resources/assets/sass/app.scss
This PR will:
* Fixes homepage modal background color
=> NOISS Fixes silver modal background style

package-lock.json, package.json, resources/assets/js/ckeditor.js, webpack.mix.js
This PR will:
* Adds horizonal line plugin to ckeditor5
* Close #277
=> #277 Adds horizontal line plugin to ckeditor5

app/Console/Commands/OnlineControllerUpdate.php
This PR will:
* Fixes the online controller bug
* Close #241
=> #241 Fixes online controller bug

.gitattributes, .github/workflows/build-and-deploy.yml, .github/workflows/build.yml, .github/workflows/deploy.yml, .gitignore, app/Console/Kernel.php, app/Http/Controllers/Controller.php, app/Http/Kernel.php, app/Http/Middleware/RedirectIfAuthenticated.php, app/Providers/AppServiceProvider.php, app/Providers/AuthServiceProvider.php, app/Providers/BroadcastServiceProvider.php, app/Providers/EventServiceProvider.php, app/Providers/RouteServiceProvider.php, composer.json, composer.lock, config/auth.php, config/mail.php, database/seeders/DatabaseSeeder.php, package.json, phpunit.xml, resources/assets/js/bootstrap.js, tests/CreatesApplication.php, tests/Feature/ExampleTest.php, tests/Unit/ExampleTest.php
This PR will:
* Upgrades site baseline framework to Laravel 10
* Close #263
=> #263 Upgrades site to Laravel 10 framework

.github/workflows/build-and-deploy.yml, .github/workflows/deploy.yml
This PR will:
* Purge cloudflare cache for an environment on deploy
=> NOISS Purge cloudflare cache on deploy

app/Audit.php, app/Event.php, app/Http/Controllers/AdminDash.php, database/migrations/2023_04_05_165639_update_events_add_show_assignments_column.php, resources/views/dashboard/controllers/events/view.blade.php, routes/web.php
This PR will:
* Allow event assignment visibility toggling
* Create static method for creating audit log entries
* Slightly refactor event registration toggling for cleanup
* Close #283
=> #283 Event assignment toggle

resources/views/dashboard/controllers/events/view.blade.php
This PR will:
* Fix the logic for the event assignment toggle
=> NOISS Fix logic for event assignment toggle

app/Console/Kernel.php
This PR will:
* Adds methods to the console kernel that push OnlineControllers:GetControllers output to a log file and to the wm email address
* Feature toggle: `online_controller_debug`
=> NOISS: Controller stats troubleshooting

app/Http/Controllers/ControllerDash.php, database/migrations/2023_05_10_110100_roster_ts3.php, resources/views/dashboard/controllers/profile.blade.php, routes/web.php
This PR will:
* Adds TS3 UID to user's profile and associated form
* Close #294
=> #294 Adds TS3 UID integration into user profile

app/File.php, app/Http/Controllers/AdminDash.php, database/migrations/2023_05_14_132000_update_files_add_row_separator_column.php, resources/views/dashboard/admin/files/edit.blade.php, resources/views/dashboard/controllers/files.blade.php, resources/views/site/files.blade.php, routes/web.php
This PR will:
* Allows staff to add subsection headers to each file browser tab
* Close #289
=> #289 Add row separators to file browser

app/Feedback.php, app/Http/Controllers/AdminDash.php, app/Http/Controllers/FrontController.php, resources/views/dashboard/admin/feedback.blade.php, resources/views/site/feedback.blade.php, routes/web.php
This PR will:
* Adds the ability to select a specific controller in feedback form from a URL slug (FE-requested)
* Adds form options for feedback based on an event or general ATC feedback
* Close #285
=> #285 Updates pilot feedback system

app/Console/Commands/SetmoreAppointments.php, app/Console/Kernel.php, app/Http/Controllers/ControllerDash.php, app/SetmoreAppointment.php, app/SetmoreLoad.php, database/migrations/2023_05_28_090900_setmore.php, database/migrations/2023_05_28_090900_setmore_appointments.php, resources/views/dashboard/controllers/profile.blade.php
This PR will:
* Adds Setmore reservations to a user's profile page, including trainer's name
* Close #300
=> #300 Setmore reservation display integration

resources/views/dashboard/controllers/teamspeak.blade.php, resources/views/site/teamspeak.blade.php
This PR will:
Added directions for user to link their TS3 UUID to their Dashboard
* Close #326
=> #326 Ts bot info to ts view

app/Console/Commands/RosterUpdate.php, app/Console/Commands/UpdateSoloCerts.php, app/Console/Commands/VisitAgreement.php, app/Http/Controllers/AdminDash.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/TrainingDash.php, config/vatusa.php, database/seeders/AnnouncementSeeder.php
This PR will:
* Enable configuration of the VATUSA baseurl (moved out of #335)
=> NOISS enable configuration of the vatusa API baseurl

app/Http/Controllers/ControllerDash.php
This PR will:
* Fix event validation and actually run it
=> NOISS hotfix event validation

app/Helpers/TimezoneHelper.php
This PR will:
* Handle historic invalid times more gracefully, ex: "2200 [invalid]" instead of just crashing
* Close #355
=> #355 hotfix historic events

app/Http/Controllers/TrainingDash.php
This PR will:
* Updates training ticket & OTS email CC address from ta@ztl to training@ztl at TA's request
=> Update training ticket & OTS CC email address

resources/views/inc/sidebar.blade.php
This PR will:
* Updates link on controller dashboard menu to TS3 info blade
=> NOISS: Corrects TS3 Info Broken Link

app/ControllerLog.php
This PR will:
* Corrects local hero SQL statement by including GSO in the sum and removing duplicate airfields
=> NOISS: Fixes Local Hero SQL statement

resources/views/site/staff.blade.php
This PR will:
* Adds description to ATA under staff page
* Close #359
=> #359 - Add ATA Job Description

app/Http/Controllers/ControllerDash.php
This PR will:
* Allow users to leave fields blank to signup for the whole event
=> NOISS allow users to leave fields blank to signup for the whole event

resources/views/dashboard/admin/roster/edit.blade.php
This PR will:
* Adds hidden status field (required form element) into visitor form
* Close #364
=> #364 Corrects visitor roster edit bug

app/Http/Controllers/TrainingDash.php, app/TrainingTicket.php, database/migrations/2023_08_28_115131_update_training_tickets_add_monitor.php, resources/views/dashboard/training/edit_ticket.blade.php, resources/views/dashboard/training/new_ticket.blade.php, resources/views/dashboard/training/tickets.blade.php
This PR will:
* Refactors the training ticket list view - consolidates code/improves maintainability of tab view
* Adds controller monitoring approved 'blue' highlight in table list view
* Fixes bug that incorrectly displayed exam score when highest graded attempt wasn't the last attempt
* Removes old code and comments, cleans several files
* Close #350, #353
=> #350, #353 Refactor training ticket view

app/Http/Controllers/ControllerDash.php, database/migrations/2023_09_09_150532_update_event_registration_add_remarks.php, resources/assets/sass/app.scss, resources/views/dashboard/controllers/events/view.blade.php
This PR will:
* Add a long-form event remarks field for specific position requests
* Close #324
=> #324 Feat event remarks again

app/Http/Controllers/TrainingDash.php
This PR will:
* Corrects an issue where email send failures when submitting a training ticket caused a 500 error and stopped execution. This prevented the ticket from getting submitted to VATUSA.
* Close #372
=> #372 Adds error handling to training ticket email

app/Http/Controllers/FrontController.php, resources/views/dashboard/admin/roster/vis_index.blade.php
This PR will:
- Create new visit request if old request hasn't been updated in 90 days or more
- Correct old visit request logic by now displaying when request < 90 days old was last updated
=> #322 correct subsequent visit requests

app/Console/Commands/SupportEvents.php
This PR will:
* Pull FNOs for Friday instead of Saturday
=> NOISS Pull FNOs for Friday, not Saturday

app/Http/Controllers/FrontController.php
This PR will:
* Correct online badge order for ATL and CLT Cab positions
* Close #376
=> #376 Fix position online badge order

app/ControllerLog.php, app/Http/Controllers/AdminDash.php, app/Http/Controllers/ControllerDash.php, app/LocalHeroChallenges.php, database/migrations/2023_09_15_132133_challenge_config.php, resources/views/dashboard/admin/bronze-mic.blade.php, resources/views/dashboard/dashboard.blade.php, routes/web.php
This PR will:
* Implements configurable monthly challenges for the local hero award
* Adds a management panel to setup monthly challenges
* Creates a news item when challenges are saved as an announcement to membership/pilots
* Implements dynamic SQL statements to pull hours based on selected position criteria
* Close #360
=> #360 Implement local hero challenges

app/Http/Controllers/RealopsController.php, app/Importers/RealopsFlightImporter.php
This PR will:
* Add basic field format validation to the realops CSV upload
* Close #233
=> #233 Basic realops csv validation

app/Http/Controllers/FrontController.php
This PR will:
* Check for ATC before sorting position array
* Close #376
=> #376 Check for atc being on before sorting

app/Airport.php, app/Console/Commands/FetchMetar.php, app/Http/Controllers/ControllerDash.php
This PR will:
* Updates NWS API endpoints for METAR & TAF data calls
* Cleans code
* Adds protection against API 404 errors from NWS
* Close #400
=> #400 Updates NWS API Endpoints

app/Http/Controllers/FrontController.php
This PR will:
* Allow pilots to give feedback based on CID in addition to name (in compliance with CoC A4b)
* Close #399
=> #399 Add CIDs to feedback select

app/Http/Controllers/ControllerDash.php, app/Http/Controllers/TrainingDash.php, resources/views/dashboard/controllers/profile.blade.php, resources/views/dashboard/training/statistics.blade.php
This PR will:
* Prevents crash of TA dashboard when Setmore API cannot be contacted
* Displays a warning on the TA dashboard and controller profile views when Setmore API cannot be contacted
* Close #412
=> #412 Adds graceful degradation to Setmore API calls

.github/ISSUE_TEMPLATE/story-template---internal-use-only.md
This PR will:
* Adds XD notes section to the story template
=> NOISS: Updates Story Template

resources/views/dashboard/controllers/staff.blade.php, resources/views/site/staff.blade.php
This PR will:
* Update ATM's description
* Close #426
=> #426 Update ATM description

resources/views/dashboard/dashboard.blade.php
This PR will:
* Replaces the button link to Setmore on the controller dashboard with a link to EA
=> NOISS: Replace dashboard Setmore link with EA link

resources/views/errors/503.blade.php
This PR will:
* Fix the margin for the 503 display page (no margin at the bottom of the box)
=> NOISS Fix margin for 503 display

app/Http/Controllers/ControllerDash.php, resources/views/dashboard/controllers/profile.blade.php
This PR will:
* Fixes the profile integrations due to rollback to EA v1.4.3
=> NOISS: Corrects EA profile integration

resources/assets/js/mix/filebrowser.js, resources/assets/js/mix/pilots_guide.js, resources/assets/js/mix/realops.js, resources/assets/js/mix/trainingticket.js
This PR will:
* Binds JS functions to window scope for webpack wrapper
* Close #472
=> #472 Exposes JS functions to window scope

app/Http/Controllers/FrontController.php
This PR will:
* Corrects a bug in FrontController - old API endpoint for aviation weather services that was throwing a 403 to the blade
* Close #469
=> #469 Corrects airport search Wx bug

app/Exports/RealopsExport.php, app/Http/Controllers/RealopsController.php, resources/views/dashboard/admin/realops/index.blade.php, routes/web.php
This PR will:
* Adds a routine to export realops flight data to csv format from the admin realops view
* Close #234
=> #234 Realops flight export

app/Http/Controllers/AdminDash.php
This PR will:
* Fixes a bug that prevents staff role assignment. Bug was introduced during the roster refactor
* Close #471
=> #471 Fixes staff role assignment bug

app/Console/Commands/SupportEvents.php, app/Event.php, resources/views/dashboard/controllers/events/index.blade.php, resources/views/dashboard/controllers/events/view.blade.php
This PR will:
* Update unverified support events when updating from VATUSA
* Use arrays to be more readable for event status, type, and reg
* Close #371
=> #371 Update unverified support events on VATUSA update

app/Console/Commands/UploadTrainingTickets.php, app/Console/Kernel.php, app/Http/Controllers/TrainingDash.php, app/TrainingTicket.php, database/migrations/2024_03_07_202803_training_tickets_upload_status.php, resources/views/dashboard/training/view_ticket.blade.php
This PR will:
* Add an hourly command to sync training tickets with VATUSA
* Remove VATUSA ticket syncing from the creation logic
* Show VATUSA ticket sync status on training tickets
* Close #443
=> #443 Batch Training Ticket VATUSA Sync

app/Http/Controllers/ControllerDash.php
This PR will:
* Wrap connections to the EA db such that it doesn't crash the profile page if the EA database is unreachable (such as in local development)
* Close #500
=> #500 don't crash if EA db is not reachable

app/Http/Controllers/Auth/LoginController.php
This PR will:
* Fix a typo made in #501 to un-break the login routine in production environments.
=> NOISS: Hotfix login typo

README.md
This PR will:
* Fix README formatting errors (NOISS)
=> NOISS Fix README Typos

app/Console/Commands/FlightawareImport.php, app/Exports/RealopsExport.php, app/Http/Controllers/RealopsController.php, app/Importers/RealopsFlightImporter.php, app/RealopsFlight.php, database/migrations/2024_03_18_012142_rename_realops_est_arr_time_to_est_time_enroute.php, resources/assets/js/mix/realops.js, resources/views/dashboard/admin/realops/create.blade.php, resources/views/dashboard/admin/realops/edit.blade.php, resources/views/dashboard/admin/realops/index.blade.php, resources/views/emails/realops/assigned_flight.blade.php, resources/views/emails/realops/bid.blade.php, resources/views/emails/realops/flight_updated.blade.php, resources/views/site/realops.blade.php
This PR will:
* Replace ETA with ETE on everything related to realops
* **Truncate the realops flights database when migrations are run against this PR**
* Close #236
=> #236 replace ETA with ETE for realops stuff

resources/assets/js/mix/pilots_guide.js
This PR will:
* Fixes an error introduced by mix update that prevents ramp status map from loading
* Close #512
=> #512 Fix minor JS errors

.github/workflows/deploy.yml
This PR will:
* Clear cloudflare cache based on wildcard
=> NOISS Clear cloudflare cache based on wildcard

app/Http/Controllers/AdminDash.php, resources/views/dashboard/admin/events/edit.blade.php, resources/views/dashboard/admin/events/new.blade.php
This PR will:
* Add support for a URL for event banner upload
* Close #487
=> Add support for event banners with URL

resources/views/dashboard/controllers/profile.blade.php
This PR will:
* Fix capitalization error within the profile.blade.php file tooltip
=> NOISS: Fix capitalization errors in tooltip

app/Console/Commands/FlightawareImport.php
This PR will:
* Fix broken flightaware import as a result of #507
=> NOISS fix flightaware import task

resources/views/site/visit.blade.php
This PR will:
* Updates the visitor requirements on our visitor form to be consistent with recent changes to DP001
=> NOISS Update visitor form policy requirements

app/Http/Controllers/TrainingDash.php, database/migrations/2024_04_28_234543_remove_ots_reports.php, resources/views/dashboard/training/ots-center.blade.php
This PR will:
* Remove file uploads from OTS
* Close #561
=> #561 remove file uploads from ots system

.github/workflows/deploy.yml, app/Console/Kernel.php, app/Http/Controllers/AdminDash.php, app/ScheduleMonitorTasks.php, composer.json, composer.lock, config/schedule-monitor.php, database/migrations/2024_05_06_151036_create_schedule_monitor_tables.php, resources/assets/js/mix/copy_to_clipboard.js, resources/assets/js/mix/filebrowser.js, resources/views/dashboard/admin/background-monitor.blade.php, resources/views/inc/sidebar.blade.php, routes/web.php
This PR will:
* Implement a scheduled task monitor
* Close #544
=> #544 Scheduled Task Monitor

app/Http/Controllers/RealopsController.php, app/RealopsPilot.php, resources/views/dashboard/admin/realops/index.blade.php, resources/views/site/realops.blade.php, routes/web.php
This PR will:
* Allow realops pilots to bid more than 1 flight
* Close #538
=> #538 Realops: Bid multiple flights

resources/views/dashboard/admin/roster/edit.blade.php, resources/views/dashboard/controllers/events/view.blade.php, resources/views/dashboard/training/edit_ticket.blade.php, routes/web.php
This PR will:
* Corrects minor errors associated with Spatie html builder rollout
=> NOISS: Spatie rollout bugfix

app/Http/Controllers/AdminDash.php, app/Permission.php, app/Role.php, app/Team.php, app/User.php, composer.json, composer.lock, config/database.php, config/laratrust.php, routes/web.php
This PR will:
* Updates underlying Laravel framework to v11
* Close #414
=> #414 Upgrade site to Laravel 11 baseline

app/Console/Commands/RosterUpdate.php, app/Http/Controllers/RosterController.php
This PR will:
* Prevents inactive staff from being displayed on staff view
* Close #583
=> #583 Fixes staff view bug

resources/views/site/realops.blade.php
This PR will:
* @iccowan found 3x more typos that I made during the Spatie update... simple bugfix to correct some issues in the realops blade
=> NOISS: Fixes Spatie HTML template typos

resources/views/dashboard/admin/realops/index.blade.php, resources/views/dashboard/controllers/events/index.blade.php, resources/views/inc/sidebar.blade.php, routes/web.php, scripts/docker-compose.yml
=> #550 Add events team to realops page

resources/views/dashboard/admin/email/send.blade.php
This PR will:
* Adds ']' closure in admin email blade to correct bug
=> NOISS: Fixes closure bug in blade

app/Http/Controllers/ControllerDash.php, resources/views/dashboard/dashboard.blade.php
This PR will:
* Refactors the dashboard controller to reduce unnecessary/extraneous code in the award display backend
* Fixes static 4-digit year display text in blade
=> NOISS: Refactor dashboard awards

app/Console/Commands/SupportEvents.php, app/EventDenylist.php, app/Http/Controllers/AdminDash.php, database/migrations/2024_07_19_213434_create_event_denylist_table.php, database/migrations/2024_07_19_225435_create_event_denylists_table.php, resources/assets/js/mix/event_index.js, resources/views/dashboard/admin/events/denylist.blade.php, resources/views/dashboard/controllers/events/index.blade.php, resources/views/dashboard/controllers/events/view.blade.php, resources/views/inc/sidebar.blade.php, routes/web.php
This PR will:
* Implement a denylist system when deleting Events with a non-null vatsim ID.
* Close #370
=> #370 support events denylisting

resources/views/emails/visit/accept.blade.php, resources/views/emails/visit/new.blade.php, resources/views/emails/visit/reject.blade.php
This PR will:
* Updates visitor email content
* Close #619
=> #619 Update visitor email content

app/Console/Commands/RosterUpdate.php, app/User.php, database/migrations/2024_09_06_134830_roster_add_last_promotion.php, resources/views/dashboard/training/tickets.blade.php
This PR will:
* Pulls last promotion date from VATUSA API during roster sync
* Formats and displays last promotion date on ticket list view (user request)
* Close #621
=> #621 Adds controller promotion info to ticket list

resources/views/dashboard/admin/realops/edit.blade.php
This PR will:
* Fix a typo in the realops edit page
=> NOISS Fix realops edit view typo

app/Http/Controllers/FrontController.php
This PR will:
* Allow ReCaptcha to fail on public forms locally for testing
=> NOISS Allow recaptcha to fail on local

app/Http/Controllers/ControllerDash.php
This PR will:
* Fixes the broken totalizer line in the training metrics
=> NOISS: Fix training metrics totalizer

app/Console/Commands/UploadTrainingTickets.php, app/Http/Controllers/TrainingDash.php, app/TrainingTicket.php, database/migrations/2024_09_16_211110_add_draft_col_to_training_tickets.php, database/migrations/2024_09_16_211920_training_tickets_add_nullables.php, resources/views/dashboard/training/edit_ticket.blade.php, resources/views/dashboard/training/new_ticket.blade.php, resources/views/dashboard/training/tickets.blade.php, resources/views/dashboard/training/view_ticket.blade.php, routes/web.php
This PR will:
* Add functionality to save training tickets as drafts
* Prevent draft tickets from uploading to VATUSA
* Change training ticket displays to show draft tickets
* Close #616
=> #616 Training Ticket Drafting

resources/views/dashboard/admin/realops/create.blade.php, resources/views/dashboard/admin/realops/edit.blade.php
This PR will:
* Fix realops form not submitting.
* Fix incorrect wording of fields.
* Close #655
=> #655 realops create flight not working

app/LiveEvent.php
This PR will:
* Forces method to return boolean (bugfix)
=> NOISS: Fixes a typing bug in the LiveEvent model

app/Http/Controllers/AdminDash.php, app/Mail/NewTrainerFeedback.php, app/TrainerFeedback.php, resources/views/dashboard/controllers/trainer_feedback.blade.php, resources/views/emails/new_trainer_feedback.blade.php
This PR will:
* Adds a training method text helper method to display the training method in plaintext
* Adds a unique trainer feedback email notification
=> NOISS: Improve trainer feedback

app/Http/Controllers/ControllerDash.php
This PR will:
* Prevents draft tickets from being listed in the student's profile page
=> NOISS: Prevent students from seeing draft tickets

resources/views/dashboard/training/edit_ticket.blade.php
This PR will:
* Adds "Start time ET" and "OTS" fields to edit view - visible only when ticket is in draft. This normalizes the edit view with the new ticket view
=> NOISS: Normalize draft ticket view with new ticket view

resources/views/emails/training_reminder.blade.php
This PR will:
* Replaces bad variables in training reminder blade that were preventing them from sending
=> NOISS: Fix training reminder emails

app/Console/Commands/RosterUpdate.php, app/Http/Controllers/TrainingDash.php, app/User.php, database/migrations/2024_09_23_160027_update_roster_add_onboarding_complete.php, resources/views/inc/sidebar.blade.php, routes/web.php
This PR will:
* Restrict the training scheduling link to users that have completed the VATUSA basic ATC exam
* Close #613
=> #613 Restrict Training Session Scheduling Link

app/Http/Controllers/TrainingDash.php, resources/views/dashboard/training/edit_ticket.blade.php
This PR will:
* Allow deleting of draft training tickets by creator
* Close #671
=> #671 Allow deleting of draft training tickets

app/Http/Controllers/TrainingDash.php, resources/views/dashboard/training/tickets.blade.php, resources/views/dashboard/training/view_ticket.blade.php
This PR will:
* Allow all viewing all training ticket drafts
* Close #672
2 Questions Before Merging:
- Yes - trainers should be able to see their own drafts
- Yes
=> #672 Training Ticket All Drafts View

app/AcademyExam.php, app/Console/Commands/UpdateAcademyExams.php, app/Console/Kernel.php, app/Http/Controllers/TrainingDash.php, app/User.php, database/migrations/2024_10_28_011029_create_academy_exams_table.php
This PR will:
* Speed up loading time for training tickets
* Reduce DB interactions when loading tickets and pulling controllers by n = controllers
* Load academy exam report info into database on roster update to prevent waiting on VATUSA when loading tickets
=> NOISS Speed Up Training Ticket Loading

resources/views/dashboard/admin/realops/index.blade.php, resources/views/dashboard/controllers/bookings.blade.php, resources/views/inc/empty_state.blade.php, resources/views/site/realops.blade.php
This PR will:
* Make the reusable component state reusable
=> NOISS Make Empty State Component Reusable

app/User.php, database/seeders/LaratrustSeeder.php, resources/views/dashboard/controllers/roster.blade.php, resources/views/inc/sidebar.blade.php, routes/web.php
**Test on QA-1 only**
This PR will:
* Adds marketing role to website staff
* Close #502
=> #502 Add marketing role

resources/views/dashboard/controllers/profile.blade.php
This PR will:
* Add link to allow the student to cancel or reschedule a session.
=> Add session reschedule link - scheddy

resources/views/inc/logo.blade.php
**HOTFIX**
This PR will:
* Corrects the filename link to the December logo
=> NOISS: Fix December logo

resources/assets/js/mix/snowstorm.js, resources/views/inc/home_footer.blade.php
This PR will:
* Fix the stop snow button
=> NOISS: Fix stop snow button

app/Http/Controllers/AdminDash.php
This PR will:
* Updates TWR and APP solo cert locations from GSO to BHM to comply with vZTL ARTCC 3120.4I
=> NOISS: Update solo cert airfields

app/Http/Controllers/AdminDash.php
This PR will:
* Fixes a variable type error in the local hero config
=> NOISS: Fix type error in local hero config

app/Mail/VisitorMail.php
This PR will:
* DATM wants to be CC'd on visitor notification emails
=> NOISS: Adds DATM CC on visitor emails

resources/views/site/pilot_passport.blade.php
This PR will:
* Updates a minor omission in the pilot passport program description
=> NOISS: Updates pilot passport description

app/Console/Commands/UploadTrainingTickets.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/ControllerDash.php, app/Http/Controllers/PilotPassportController.php, app/Http/Controllers/TrainingDash.php, app/RealopsPilot.php, app/TrainerFeedback.php, app/User.php, resources/assets/sass/app.scss, resources/views/dashboard/admin/airports/index.blade.php, resources/views/dashboard/admin/calendar/index.blade.php, resources/views/dashboard/admin/feedback.blade.php, resources/views/dashboard/admin/incident_reports/index.blade.php, resources/views/dashboard/admin/roster/vis_index.blade.php, resources/views/dashboard/admin/scenery/index.blade.php, resources/views/dashboard/admin/trainer_feedback.blade.php, resources/views/dashboard/controllers/events/index.blade.php, resources/views/dashboard/controllers/files.blade.php, resources/views/dashboard/controllers/profile.blade.php, resources/views/dashboard/training/ots-center.blade.php, resources/views/dashboard/training/tickets.blade.php, resources/views/inc/scenery_index.blade.php, resources/views/site/airports/index.blade.php, resources/views/site/files.blade.php, resources/views/site/pilot_guide_atl.blade.php
This PR will:
* Add an empty state for empty tables on most major tables
* Close #698
=> #698 Add Empty State for Empty Tables

app/LocalHeroChallenges.php
This PR will:
* Adds a few missing TRACONs to the local hero challenge
=> NOISS: Add missing facilities to local hero challenge

app/Console/Commands/UpdateAcademyExams.php
This PR will:
* Add SUP/ADM users to exam check
=> NOISS Add SUP/ADM to user exam check

app/Console/Commands/EventStatReport.php, app/Http/Controllers/AdminDash.php, resources/views/dashboard/admin/events/report.blade.php
This PR will:
* Add the SUP/ADM roles to event reports
* Protect against reports saved without SUP/ADM roles
* Automatically format airport names for event reporting
=> NOISS Event Report Bug Fixes

composer.json, composer.lock
This PR will:
* Updates to Laravel 12.x framework
* Updates required dependencies
* Forked the abandoned laravel-timezone library for compatibility
* Close #741
=> #741 Use Laravel 12 framework

app/Http/Controllers/ControllerDash.php
This PR will:
* Fixes a bug that was causing the local hero challenge title to display improperly
* Close #749
=> #749 Fix local hero challenge title display error

app/Http/Controllers/TrainingDash.php, app/Mail/StudentComment.php, resources/views/emails/student_comment.blade.php
This PR will:
* Sends an email notification to the INS/MTR when a student creates a comment on the ticket
* Close #685
=> #685 Creates student comment emails

app/Http/Controllers/AdminDash.php, resources/assets/js/mix/permalink_field.js, resources/views/dashboard/admin/files/upload.blade.php
This PR will:
- Add new UI on the file upload page for selecting preexisting permalinks
- Allow staff to "update" preexisting files and reassign their permalinks to the new files
- Removes the old file from the explorer
* Close #755
=> #755 Reassign Existing Permalink

app/Http/Controllers/TrainingDash.php, app/Livewire/TaStatsGeneral.php, app/Livewire/TaStatsMonthly.php, app/TrainingTicket.php, composer.json, composer.lock, package-lock.json, package.json, public/chart.js/chart.js, resources/assets/js/app.js, resources/views/dashboard/training/statistics.blade.php, resources/views/livewire/ta-stats-general.blade.php, resources/views/livewire/ta-stats-monthly.blade.php, webpack.mix.js
This PR will:
* Rebuilds the TA dashboard into a tabbed display
* Breaks-up stats loading into separate livewire components for faster loading/dynamic response
* Allows reload of content via AJAX instead of reload
* Introduces new graphs requested by TA and DATM
* Updates TA's monthly report
* Close #736
=> #736 TA dashboard redesign

app/Http/Controllers/TrainingDash.php, resources/assets/js/ckeditor.js, resources/assets/sass/mix/trainingticket.scss, resources/views/dashboard/training/view_ticket.blade.php, routes/web.php
This PR will:
* Fix the bug with Ckeditor not allowing images to be uploaded
* Implements a custom image upload adapter for the Ckeditor build
* Protects against the user submitting tickets without an image being fully uploaded
* Uploads the image to storage
* Close #761
=> #761 Fix Ckeditor Image Upload

resources/assets/js/bootstrap.js, resources/assets/js/mix/sidebar.js, resources/assets/sass/app.scss, resources/assets/sass/mix/sidebar.scss, resources/views/inc/sidebar.blade.php
This PR will:
* Refactors the sidebar menu using modern bootstrap techniques
* Removes css margin/null tricks
* Corrects zero-space error caused by expanding sidebar
* Close #645
=> #645 Refactor sidebar menu

tests/Browser/PilotPassportChallengeTest.php
This PR will:
* Fix errant browser test failures associated with pilot passport enrollment view
=> NOISS: Fix errant browser test issues

resources/views/dashboard/admin/roster/vis_index.blade.php
This PR will:
* Add a text box when data is empty for the visit requests table
* Close NOISS
=> NOISS: Add text to when table is empty on visit requests page

resources/views/inc/sidebar.blade.php
This PR will:
* Removes "new" badge from sidebar menu merch store link
* Close #795
=> #795 Remove "new" badge

app/Console/Commands/FetchMetar.php, app/Http/Controllers/ControllerDash.php, resources/views/dashboard/controllers/airport.blade.php, resources/views/site/airports/view.blade.php
This PR will:
* Allow METARs and TAFs to update using the new API
* Cleanup how METARs and TAFs are pulled and stored
* Allow special case airports (no airport diagram, no TAF, no METAR) to still display properly when searched from the controller dashboard
=> NOISS Fix METARs and TAFs not updating

app/Console/Commands/FetchMetar.php
This PR will:
* Prevent the UpdateWeather command from failing when no airports are configured
=> NOISS: Prevent UpdateWeather command failures due to no stations
