app/Http/Controllers/AdminDash.php

Fixed simple typo, would show as `NAME made \"News Name\" visible` now will show as `NAME made News Name visible`.

Fixed audit log typo when changing news visibility

---

app/TrainingTicket.php
resources/views/dashboard/training/edit_ticket.blade.php
resources/views/dashboard/training/new_ticket.blade.php
resources/views/dashboard/training/tickets.blade.php

Added another ticket option for mentors titled **"Recurrent Training"**. Will display in the **"Other"** tab when viewing a controller's tickets.

Add "Recurrent Training" training lesson to the tickets system

---

resources/views/emails/training_ticket.blade.php

Fixes an error with the displayed time zone in emails that are sent to a student after a training ticket is entered. Bug was reported today by Ford Grable in Discord.

Bugfix: email template timezone

---

resources/views/dashboard/admin/roster/edit.blade.php

This PR will:
* Adds an option for non-staff member instructor/mentors to add a solo cert on the roster edit page for a user
* Close #198

Fixes missing solo cert menu option

---

app/Http/Controllers/AdminDash.php

This PR will:
* Adds functionality requested by TA in Discord
* Allows an instructor or mentor to remove a member's solo certification
* Change from present system that required the solo cert to auto-expire after 30-days
* Close #205

Allow INS/MTR to remove twr solo cert

---

.github/workflows/build.yml

This PR will:
* Update the build/validate workflow to use `setup-node` to `v3` to align with the build/build workflow

NOISS Update setup-node in build workflow to v3

---

app/Http/Controllers/Auth/LoginController.php

This PR will:
* Fix the issue of the realops pilot ID not being set correctly including...
* Inadvertent ability to book multiple flights
* Inability to cancel flights
This should be tested with multiple people prior to merging to ensure that the issue is corrected, and merging should be held until the current realops databases can be dumped as this will break the current implementation.

NOISS Fix realops pilot ID assignment

---

app/Http/Controllers/AdminDash.php

This PR will:
* Makes file titles safe as file names by removing special characters before storing the file
* Close #273

#273 Fix filename upload bug

---

app/Exceptions/Handler.php
resources/views/errors/500.blade.php

This PR will:
* Adds a method to the error handler that filters exception messages, removing POST/GET parameters
* Modifies the HTTP 500 error page to utilize the generated safe error message
* Close #243

#243 Adds logic to create a safe error message

---

resources/views/dashboard/admin/roster/edit.blade.php

This PR will:
* Fixes the roster edit menu text to correct a typo... "Montoring" to "Monitoring"

NOISS: Fixes a typo in the select menu option text

---

app/Http/Controllers/AdminDash.php

This PR will:
* Fixes a bug identified by Simon Heck in Discord that prevented INS/MTR non-staff members from editing the solo fields on a member's roster edit page.

NOISS: Allows ins/mtr to update solo fields in roster

---

app/Console/Commands/ARTCCOverflights.php

This PR will:
* Fix an error found in the laravel log file: [2023-04-10 11:10:04] production.ERROR: foreach() argument must be of type array|object, null given {"exception":"[object] (ErrorException(code: 0): foreach(
) argument must be of type array|object, null given at /home/dh_k4agrs/ztl/ztlartcc.org/app/Console/Commands/ARTCCOverflights.php:48)

NOISS Add null API reply protection to ARTCC Overflights method

---

app/Http/Controllers/AdminDash.php
database/migrations/2023_05_14_132500_update_event_registration_add_position_id_detail_column.php
resources/views/dashboard/controllers/events/view.blade.php
resources/views/emails/event_reminder.blade.php

This PR will:
* Addresses an issue where event sign-up information is visible in the registration form before the event visibility is toggled on
* Adds position assignment detail field to EC's controls to input specific position identifier (ex. C43) without overriding the start or end time fields
* Allows staff to delete member event registrations (to remove duplicates)
* Close #275 
* Close #286 
* Close #297

#275, #286, #297: Multiple modifications to event registration methods

---

app/Console/Commands/EventEmails.php
resources/views/emails/event_reminder.blade.php

This PR will:
* Corrects a bug associated with the update to email event reminders. $position->status is out of scope in the blade, causing a 500 error when executing the email reminder command.
* I overlooked the status == 1 limitation which would prevent controllers with an event registration but no position assignment from getting a generic reminder email (EC's request). This PR removes the status == 1 restriction.

NOISS: Correct event reminder email bug

---

app/Http/Controllers/ControllerDash.php
resources/views/dashboard/dashboard.blade.php

This PR will:
* Removes the duplicative online controller display in the body of the dashboard (this info is now displayed on the left-side nav area)
* Converts the event banner display in the body of the dashboard into a carousel to prevent vertical growth of the view when many events are active
* Close #301

#301 Cleans up controller dashboard

---

app/Http/Controllers/AdminDash.php
app/Http/Controllers/ControllerDash.php
app/User.php
database/seeders/LaratrustSeeder.php
resources/views/dashboard/admin/roster/edit.blade.php
resources/views/dashboard/controllers/events/view.blade.php
resources/views/inc/sidebar.blade.php

This PR will:
* Adds a "AEC Ghost" role, allowing the EC to grant AEC permissions to someone without that user being assigned the AEC tag on the roster or being listed as an AEC on the staff page.
* Adds an "Event Team" role, allowing assigned users to see hidden events and permission assignments (read-only)
* Close #303 
* Close #304

#303, #304 Updates events team permissions & roles

---

resources/views/dashboard/controllers/events/view.blade.php

This PR will:
* Fix a bug currently preventing members with the events_team role from viewing event signups when they are hidden

NOISS: Adds events_team visibility permission

---

resources/views/dashboard/admin/roster/edit.blade.php

This PR will:
* Resolves a bug pointed out by training staff where length inputs in the tower solo fields roster edit form can exceed the database column size and throw an error. Sets maxlength of input field to 255, matching VARCHAR database column.

NOISS: Sets tower solo fields input maxlength

---

resources/views/site/teamspeak.blade.php

This PR will:
* Add a link on the Teamspeak info page prompting to review the full Teamspeak and discord policy, linking to the permalink
* Close #325

#325 Add link to teamspeak policy on teamspeak info page

---

app/Http/Controllers/AdminDash.php
app/User.php
resources/views/dashboard/admin/roster/edit.blade.php
resources/views/dashboard/controllers/roster.blade.php
routes/web.php

This PR will:
* Breaks out the events positions into a separate select menu in the roster edit view
* Gives the EC limited permissions to grant/revoke AEC, AEC-Ghost, and Events Team roles
* Adds special events team badges that are viewable only by staff on the roster list view
* Appropriate backend support added for the functions described above
* Close #311

#311 Add limited roster edit perms for EC

---

resources/views/site/pilot_guide_atl.blade.php

This PR will:
* Fix a typo in the pilot's guide under Push & Start
* Close #337

#337 Fixes typo in pilot's guide

---

resources/views/dashboard/controllers/profile.blade.php
resources/views/inc/dashboard-head.blade.php

This PR will:
* Move the broadcast email toggle to the profile page, and out of the dashboard header
* Close #345

#345 Move broadcast email toggle to profile, out of dashboard header

---

app/Console/Commands/ARTCCOverflights.php

This PR will:
* Updates the URL to the ARTCC Overflight API (Denver's API changed URLs)

NOISS: Fix Overflight API URL

---

app/Http/Controllers/AdminDash.php

This PR will:
* EC noted that although he has roster access, saving a user results in a 500 error. Upon closer inspection, found out that inadvertently left events permission off of the roster save methods. Added appropriate conditionals to fix this issue.

NOISS: Fixes roster save flow for EC

---

app/Console/Commands/SupportEvents.php
app/Console/Kernel.php
app/Event.php
app/Http/Controllers/AdminDash.php
database/migrations/2023_09_09_163102_update_events_add_type.php
database/migrations/2023_09_09_165648_update_events_add_vatsim_id.php
resources/views/dashboard/admin/events/edit.blade.php
resources/views/dashboard/admin/events/new.blade.php
resources/views/dashboard/controllers/events/index.blade.php
resources/views/dashboard/controllers/events/view.blade.php
routes/web.php

This PR will:
* Automate the creation of support events
* Add a new console command to create support events
* Slightly change the event index view to show details on event types
* Slightly change the event create and edit views to add a field for event types
* Add a new column to `events` to record the event type
* Close #351

#351 Automate support events

---

resources/views/dashboard/admin/roster/edit.blade.php

This PR will:
* Limits events team roster edit permissions to the EC
* Close #398

#398 Corrects events team roster edit perms

---

app/Console/Commands/RosterUpdate.php

This PR will:
* Adds logic to the roster update console command that pulls visitor information from VATUSA and updates the ZTL roster
* Close #406

#406 Adds visitor auto-roster update

---

resources/views/inc/navbar.blade.php

This PR will:
* Removes VATSTAR link from the navbar - VATSTAR is shutting down on 1 Jan 2024

NOISS: Removes VATSTAR link from the Navbar

---

app/Console/Commands/RosterUpdate.php
app/Listeners/ValidateEmail.php
app/Providers/EventServiceProvider.php

This PR will:
* Adds protection to the email routine through a listener and embedded 'to' address validator
* Fixes the issue that was wiping email addresses from the visitor roster (VATUSA API authentication)
* Close #432

#432 Fix null email issues

---

app/Console/Commands/RosterUpdate.php
app/User.php
database/migrations/2024_01_18_102000_update_roster_add_privacy.php
resources/views/site/roster.blade.php

This PR will:
* Pulls name privacy flag from VATUSA during the daily roster update routine
* When flag is set, will replace a member's last name with their CID on the public-facing roster
* Close #410

#410 Implement name privacy

---

resources/views/dashboard/admin/roster/edit.blade.php

This PR will:
* Fixes a bad constant name in the roster edit view that was improperly allowing edit access to ATL LCL cert controls

NOISS: Corrects improper roster variable name

---

resources/views/site/pilot_guide_atl.blade.php

This PR will:
* [fixed typo in Clearance section now should say "amount"]
* Close #482

#482 Typo in Clearance Delivery Section of Pilot Guide

---

resources/assets/sass/app.scss

This PR will:
* Corrects a bug in the stats view table cell coloring by adding the td selector to color selectors in sass source file
* Close #476

#476 Adds selectors for stats view cell coloring

---

database/migrations/2024_03_06_000921_add_primary_key_to_roster.php

This PR will:
* Add `id` as the primary key to the roster table

NOISS Add primary key of id to roster

---

app/Console/Commands/RosterUpdate.php

This PR will:
* Allow an email to be set when running the roster update locally. If no email is specified, a default email will be used
* Close #463

#463 Allow manual email when updating roster locally

---

.github/CODEOWNERS

This PR will:
* Update the CODEOWNERS file so that @ZTL-ARTCC/code_reviewers is marked as the code owner instead of web_team, so that it's the people who are marked for review

NOISS Update CODEOWNERS to be code_reviewers instead of web_team

---

resources/views/dashboard/controllers/profile.blade.php

This PR will:
* Between Email and CID add a new item Name Privacy with status Enabled or Disabled. Name privacy flag is set in the user model with the flag $user->name_privacy as a boolean and automatically synced from VATUSA (it's not set on our website, just synced from USA's database)
* Add a tooltip next to the name privacy field (like the email field) that says Click here to update - link to VATUSA profile and the link should go to: https://www.vatusa.net/my/profile
* Close #498

#498 Add privacy flag to user profile

---

app/Console/Commands/UploadTrainingTickets.php

This PR will:
* Corrects typo in VATUSA position map from `CTL_DEL` to `CLT_DEL`

NOISS: Fix position id typo

---

app/Http/Controllers/Auth/LoginController.php
routes/web.php

This PR will:
* When I updated Laratrust to 8x, an unmerged change didn't get updated to the new method call. This updates the method call to properly assign the WM role to local users in a dev environment

NOISS: Correct local dev WM role assignment

---

app/Event.php
app/Http/Controllers/ControllerDash.php
app/Providers/AppServiceProvider.php
resources/views/dashboard/controllers/events/index.blade.php

This PR will:
* Paginates the show events view for events staff only to 10 items per load. This view gets slower to load each time we add additional events due to all of the banners. Paginating this view will maintain a consistent load experience independent of the number of events/banners.
* No change to the events view for non-staff (view will still show all active events)
* Cleans up some sloppy string-to-timestamp code that I previously wrote by shifting the conversion into a model attribute so it is chainable

NOISS: Paginate events view

---

resources/views/dashboard/admin/calendar/edit.blade.php

This PR will:
* Fix a small issue with displaying the Edit Calendar entry by closing a bracket that wasn't closed before and caused an internal website error

NOISS: Fix bracket bug in Edit Calendar

---

app/Console/Commands/RosterUpdate.php
resources/views/dashboard/controllers/profile.blade.php

This PR will:
* Fixes a minor bug associated with updating the roster discord_id field for visitors

NOISS: Correct roster update discord_id

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/setup-variables.yml

This PR will:
* Upgrade the following actions to v4
* actions/checkout
* actions/cache
* actions/setup-node
* actions/upload
* actions-download

NOISS Upgrade actions to v4

---

app/Http/Controllers/ControllerDash.php
app/Http/Controllers/TrainingDash.php
resources/assets/js/mix/sidebar.js
resources/assets/sass/mix/sidebar.scss
resources/views/inc/sidebar.blade.php

This PR will:
* Finally... gives us the collapsible menu that we deserve (submenus auto-collapse with accordion-like behavior)
* Adds some training statistics to the sidebar

NOISS: Refactor sidebar menu

---

app/Console/Commands/PilotPassportActivityUpdate.php

This PR will:
* Updates the pilot passport update routine to fix a minor bug that prevents multiple achievements from being logged

NOISS: Fix pilot passport achievement awards

---

database/seeders/PilotPassportAirfieldSeeder.php

This PR will:
* Corrects 2 errors in the pilot passport airfield descriptions
* Already corrected on prod since the error is in the database seeder

NOISS: Fix 2x airfield description errors

---

database/seeders/PilotPassportAirfieldSeeder.php

This PR will:
* Adds an airfield description to the seeder for EUF

NOISS: Add pilot passport description for EUF

---

app/Ots.php

This PR will:
* An instructor created an OTS for a training type that should never get an OTS (Mentor Training) which caused the OTS center to fail with an error. This fix ensures that the OTS center position lookup always returns a string value.

NOISS: Prevent OTS center unknown position fail

---

app/Http/Controllers/TrainingDash.php

This PR will:
* Allow the TA stats to show training staff that are facility visitors (such as VATUSA staff who hold a MTR or INS rating at ZTL)

NOISS: Update TA Stats Filters

---

app/Http/Controllers/TrainingDash.php

This PR will:
* Training stats were not counting unrestricted ground sessions due to a logic error.

NOISS: Fix training stats logic error

---

app/Class/PointInPolygon.php
app/Console/Commands/ARTCCOverflights.php

This PR will:
* Replaces deprecated ZDV overflights API
* Computes overflights locally
* Uses FAA's ARTCC boundary file
* Close #700

#700 Calculate ZTL overflights

---

resources/views/dashboard/admin/bronze-mic.blade.php
resources/views/dashboard/admin/roster/edit.blade.php
resources/views/dashboard/controllers/profile.blade.php
resources/views/inc/stats.blade.php
resources/views/layouts/dashboard.blade.php
resources/views/layouts/master.blade.php

This PR will:
* Updates bootstrap on both the landing page and dashboard from v4.1.0 (2018) to v4.6.2 (2022)
* Interim step on the path to v5
* Resolves long list of vulnerabilities
* No breaking changes noted. Changelog here: https://github.com/twbs/bootstrap/releases?page=5
* Minor UI changes required - had to disable text wrapping in some buttons

NOISS: Bump bootstrap to v4.6.2

---

resources/views/inc/sidebar.blade.php

This PR will:
* Hides the Laratrust panel link in the sidebar menu when running in other than 'local' environments
* Panel isn't active in QA/STAG/PROD, so no need for this link to be visible... this is a dev-only feature

NOISS: Hides Laratrust panel link

---

resources/views/layouts/dashboard.blade.php
resources/views/layouts/master.blade.php

This PR will:
* Slim version of jquery doesn't have ajax capability
* Bug introduced about 2 months ago when I updated the site to bootstrap 4.6.2
* Fixes misc JS errors (ticket autosave, file browser ordering, etc)

NOISS: Change jquery dist

---

app/Http/Controllers/TrainingDash.php
resources/assets/js/mix/trainingticket.js

This PR will:
* Prevent new training ticket drafts from being created due to a tab open of a deleted ticket
* Close #776

#776 Prevent new training ticket drafts from open tab of deleted ticket

---

resources/views/dashboard/controllers/profile.blade.php

This PR will:
* Removes errant "profile." from discord role button on profile page (bad cut & paste?)

NOISS: Corrects text error on profile page

---

app/Http/Controllers/AdminDash.php

This PR will:
* Fix the issue where training staff are not able to remove training certifications
* Still require solo certifications to be removed by clicking the added button
* Close #797

#797 Allow Removing Roster Certifications
